app:
  name: aegis
  env: dev

logging:
  level: INFO
  json: true
  rotate_mb: 20
  backups: 7

api:
  enabled: true
  host: 127.0.0.1
  port: 8080

embedding:
  model: sentence-transformers/all-MiniLM-L6-v2
  dimension: 384
  batch_size: 32

memory:
  relational_backend: sqlite
  vector_backend: none   # none | lancedb
  sqlite_path: ./data/aegis.db
  lancedb_uri: ./data/lancedb

security:
  keystore_path: ./data/keystore.json
  key_derivation: argon2id
  file_cipher: chacha20poly1305